import rospy
import json
import numpy as np
import torch
import random
from human_awareness_msgs.msg import PersonsList
from visualization_msgs.msg import MarkerArray
from tf2_msgs.msg import TFMessage
from view_predictions import TrajectoryEvaluator
from evaluate_jta import load_model_and_config, evaluate_real_time_data
from utils.utils import create_logger

class RealTimeDataCollector:
    def __init__(self, checkpoint_path="realeases/jta/checkpoint/checkpoint.pth.tar"):
        self.local_frames = []
        self.ego_frames = []
        self.camera_frames = []
        self.latest_robot_tf = None
        self.latest_camera_tf = None
        self.seq_len = 10
        self.interval = 5  # detection frequency is 5Hz, so interval of 5 means 1 second
        self.debug = False

        # Set random seeds for reproducibility
        random.seed(0)
        np.random.seed(0)
        torch.manual_seed(0)

        rospy.init_node('real_time_data_collector', anonymous=True)
        
        # Initialize logger
        self.logger = create_logger('')
        
        # Load model and configuration
        self.logger.info("Initializing model for real-time prediction...")
        self.model, self.config = load_model_and_config(checkpoint_path, self.logger)
        self.model.eval()  # Set to evaluation mode
        self.logger.info("Model loaded successfully!")
        
        # Initialize trajectory evaluator
        self.trajectory_evaluator = TrajectoryEvaluator()
        
        # Subscribers
        self.image_detections_sub = rospy.Subscriber('/image_detections', PersonsList, self.image_detections_callback)
        self.tf_sub = rospy.Subscriber('/combined_tf', TFMessage, self.tf_callback)
        
        # Publisher for trajectory visualization
        self.trajectory_pub = rospy.Publisher('/trajectory_predictions', MarkerArray, queue_size=10)

    def tf_callback(self, msg):
        """Extract robot transform from TFMessage"""
        if msg.transforms:
            # Since we only have one transform now, take the first one
            self.latest_robot_tf = msg.transforms[0]

    def image_detections_callback(self, msg):
        if not msg.persons:
            return

        # Debug: Log first successful message
        if len(self.local_frames) == 0:
            print(f"First person detection received with {len(msg.persons)} person(s)")
            if msg.persons:
                person = msg.persons[0]
                if hasattr(person, 'body_pose'):
                    pos = person.body_pose.position
                    print(f"Person body position: x={pos.x:.3f}, y={pos.y:.3f}, z={pos.z:.3f}")

        # Create frames from available data
        self.create_ego_frame()
        self.create_camera_pose_frame()
        self.create_local_frame(msg)
        
        # Process frames when we have enough data
        if len(self.local_frames) > self.seq_len * self.interval + 1:
            try:
                # Extract trajectory data from local frames
                X = self.extract_trajectory_data()
                
                if X is not None and len(X) > 0:
                    print(f"Extracted trajectory data shape: {X.shape}")
                    print(f"Trajectory data sample: {X[:3].tolist()}")  # Show first 3 points
                    
                    # Use the loaded model for real-time prediction
                    predictions = self.predict_trajectories(X)
                    
                    if predictions:
                        print(f"Generated {len(predictions)} trajectory predictions")
                        # Show shape of predictions
                        if isinstance(predictions, list) and len(predictions) > 0:
                            pred_array = np.array(predictions)
                            print(f"Predictions shape: {pred_array.shape}")
                            print(f"First few predictions: {pred_array[:3].tolist()}")
                    else:
                        print("ERROR: No predictions generated by the model")
                        print("This could indicate:")
                        print("1. Model input format mismatch")
                        print("2. Model output processing error")
                        print("3. Model internal error")
                        return  # Don't proceed with empty predictions
                    
                    # Create data for visualization
                    observations = [X] if X is not None else []
                    ground_truth = []  # No ground truth in real-time
                    
                    # Only visualize if we have predictions
                    if predictions:
                        # Transform observations and predictions to odom frame before visualization
                        transformed_observations = self.transform_to_odom_frame(observations)
                        transformed_predictions = self.transform_to_odom_frame(predictions)
                        
                        print(f"Original predictions sample: {predictions[:2] if len(predictions) > 1 else predictions}")
                        print(f"Transformed predictions sample: {transformed_predictions[:2] if len(transformed_predictions) > 1 else transformed_predictions}")
                        
                        # Visualize trajectories with transformed coordinates
                        #self.trajectory_evaluator.detailed_position_analysis(transformed_observations, ground_truth, transformed_predictions, self.local_frames, self.seq_len, self.interval)
                        self.trajectory_evaluator.publish_trajectories_to_rviz(transformed_observations, ground_truth, transformed_predictions)
                        
                        if self.debug:          
                            self.save_debug_data(X, predictions)
                    else:
                        print("WARNING: Skipping visualization due to empty predictions")
                else:
                    print("WARNING: No trajectory data extracted from frames")
                    
            except Exception as e:
                print(f"ERROR in prediction pipeline: {e}")
                import traceback
                print(traceback.format_exc())


    def extract_trajectory_data(self):
        """Extract trajectory data from recent local frames"""
        if len(self.local_frames) < self.seq_len:
            print(f"Not enough frames: {len(self.local_frames)} < {self.seq_len}")
            return None
            
        # Take the most recent frames according to sequence length and interval
        recent_frames = self.local_frames[-self.seq_len * self.interval:]
        print(f"Using {len(recent_frames)} recent frames")
        
        # Extract person trajectories (simplified version)
        trajectories = []
        
        # Group frames by interval to get the sequence
        for i in range(0, len(recent_frames), self.interval):
            if i < len(recent_frames):
                frame = recent_frames[i]
                frame_data = []
                
                # Extract position data for each person
                for person in frame['persons']:
                    pos = person['position']
                    frame_data.append([pos['x'], pos['y']])
                
                if frame_data:
                    trajectories.append(frame_data)
                    print(f"Frame {i//self.interval}: {len(frame_data)} persons, first pos: {frame_data[0]}")
        
        print(f"Extracted {len(trajectories)} trajectory frames")
        
        # Convert to numpy array format expected by model
        if trajectories and len(trajectories) >= 9:  # Need at least input_track_size frames
            # Take the first person's trajectory for simplicity
            # In a real implementation, you'd handle multiple people
            person_trajectory = []
            for frame_data in trajectories[:9]:  # input_track_size = 9
                if frame_data:  # If there's at least one person in this frame
                    person_trajectory.append(frame_data[0])  # Take first person
                else:
                    # If no person in frame, use last known position or zero
                    if person_trajectory:
                        person_trajectory.append(person_trajectory[-1])
                        print(f"Missing person in frame, using last known position")
                    else:
                        person_trajectory.append([0.0, 0.0])
                        print(f"Missing person in frame, using zero position")
            
            result = np.array(person_trajectory)
            print(f"Final trajectory shape: {result.shape}")
            print(f"Trajectory start: {result[0]}, end: {result[-1]}")
            return result
        else:
            print(f"Not enough trajectory frames: {len(trajectories)} < 9")
            return None

    def transform_to_odom_frame(self, points):
        """Transform points from robot frame to odom frame using latest robot TF"""
        if self.latest_robot_tf is None or points is None or len(points) == 0:
            return points
            
        try:
            # Get robot transform (base_footprint to odom)
            robot_trans = self.latest_robot_tf.transform
            robot_x = robot_trans.translation.x
            robot_y = robot_trans.translation.y
            
            # For simplicity, assuming no rotation (can be extended if needed)
            # Transform points: robot_frame_point + robot_position_in_odom = odom_frame_point
            transformed_points = []
            
            if isinstance(points, list) and len(points) > 0:
                # Check if it's a list of trajectories (observations format) or single trajectory (predictions format)
                if isinstance(points[0], list) and len(points[0]) > 0 and isinstance(points[0][0], list):
                    # List of trajectories format: [[trajectory1], [trajectory2], ...]
                    for trajectory in points:
                        transformed_traj = []
                        for point in trajectory:
                            if isinstance(point, list) and len(point) >= 2:
                                transformed_point = [point[0] + robot_x, point[1] + robot_y]
                                transformed_traj.append(transformed_point)
                        transformed_points.append(transformed_traj)
                elif isinstance(points[0], list) and len(points[0]) >= 2:
                    # Single trajectory format: [[x1, y1], [x2, y2], ...]
                    for point in points:
                        if isinstance(point, list) and len(point) >= 2:
                            transformed_point = [point[0] + robot_x, point[1] + robot_y]
                            transformed_points.append(transformed_point)
                else:
                    # Handle other list formats
                    transformed_points = points
                    
            elif hasattr(points, 'shape'):  # Numpy array
                points_copy = np.copy(points)
                if len(points_copy.shape) >= 2 and points_copy.shape[1] >= 2:
                    points_copy[:, 0] += robot_x  # Add robot x to all x coordinates
                    points_copy[:, 1] += robot_y  # Add robot y to all y coordinates
                transformed_points = points_copy
            else:
                transformed_points = points
                
            print(f"Transformed {len(points) if hasattr(points, '__len__') else 'unknown'} points to odom frame")
            print(f"Robot position: x={robot_x:.3f}, y={robot_y:.3f}")
            
            return transformed_points
            
        except Exception as e:
            print(f"Error transforming to odom frame: {e}")
            import traceback
            print(traceback.format_exc())
            return points

    def predict_trajectories(self, X):
        """Use the loaded model to predict trajectories from processed frame data"""
        try:
            if X is None or len(X) == 0:
                print("ERROR: Input X is None or empty")
                return []
            
            print(f"Input X shape: {X.shape}, dtype: {X.dtype}")
            print(f"Input X range: min={np.min(X):.3f}, max={np.max(X):.3f}")
                
            # Convert input data to the format expected by the model
            # Model expects (B, in_F, NJ, K) where:
            # B = batch size, in_F = input frames, NJ = num_people * num_joints, K = coordinates (4D)
            input_joints = torch.tensor(X, dtype=torch.float32)
            
            # The model expects 47 joints per person (token_num from config)
            # and 4D coordinates (x, y, z, confidence/visibility)
            # We only have 2D trajectory points, so we'll extend to 4D
            
            B = 1  # batch size
            in_F = input_joints.shape[0]  # input frames (9)
            J = 47  # number of joints per person (from config token_num)
            N = 1   # number of people
            NJ = N * J  # total joints (1 person * 47 joints = 47)
            K = 4   # coordinate dimensions (x, y, z, confidence) - model expects 4D
            
            print(f"Model expects {J} joints per person with {K}D coordinates")
            print(f"Creating padded input: (B={B}, in_F={in_F}, NJ={NJ}, K={K})")
            
            # Create padded joint data: (in_F, NJ, K)
            padded_joints = torch.zeros(in_F, NJ, K)
            
            # Place our trajectory data in the first joint (index 0) of each frame
            # Convert 2D (x, y) to 4D (x, y, z=0, confidence=1)
            padded_joints[:, 0, 0] = input_joints[:, 0]  # x coordinate
            padded_joints[:, 0, 1] = input_joints[:, 1]  # y coordinate
            padded_joints[:, 0, 2] = 0.0                 # z coordinate (2D data, so z=0)
            padded_joints[:, 0, 3] = 1.0                 # confidence/visibility (valid data)
            
            # Reshape to model format: (B, in_F, NJ, K)
            input_joints = padded_joints.unsqueeze(0)  # (in_F, NJ, K) -> (1, in_F, NJ, K)
            
            print(f"Reshaped input tensor shape: {input_joints.shape}")
            print(f"Non-zero joints: {torch.count_nonzero(input_joints)}")
            print(f"Sample first joint coords: x={input_joints[0,0,0,0]:.3f}, y={input_joints[0,0,0,1]:.3f}, z={input_joints[0,0,0,2]:.3f}, conf={input_joints[0,0,0,3]:.3f}")
            
            # Create padding mask with correct dimensions (B, N) not (B, NJ)
            # B = batch size, N = number of people (not total joints)
            N = 1  # number of people
            padding_mask = torch.zeros(B, N, dtype=torch.bool)  # All people are valid (not padded)
            print(f"Padding mask shape: {padding_mask.shape}")
            print(f"Valid (non-padded) people: {torch.sum(~padding_mask)}")
            
            # Get predictions using the real-time evaluation function
            print("Calling evaluate_real_time_data...")
            predictions = evaluate_real_time_data(self.model, self.config, input_joints, padding_mask)
            
            if predictions is not None:
                print(f"Raw predictions shape: {predictions.shape}")
                print(f"Raw predictions dtype: {predictions.dtype}")
                print(f"Raw predictions range: min={torch.min(predictions).item():.3f}, max={torch.max(predictions).item():.3f}")
                
                # Convert predictions back to numpy and return
                pred_numpy = predictions.detach().numpy()
                print(f"Numpy predictions shape: {pred_numpy.shape}")
                
                # Check if predictions are reasonable
                if pred_numpy.size == 0:
                    print("ERROR: Predictions tensor is empty")
                    return []
                
                # Extract the trajectory data from the prediction tensor
                # Predictions likely have shape (B, N, F, J, K) - extract the trajectory coordinates
                if len(pred_numpy.shape) == 5:
                    # Extract first person's trajectory coordinates: (B, N, F, J, K) -> (F, K)
                    trajectory_pred = pred_numpy[0, 0, :, 0, :2]  # Get first person, first joint, x,y coords
                elif len(pred_numpy.shape) == 4:
                    # If shape is (B, F, J, K)
                    trajectory_pred = pred_numpy[0, :, 0, :2]
                elif len(pred_numpy.shape) == 3:
                    # If shape is (B, F, K)
                    trajectory_pred = pred_numpy[0, :, :2]
                else:
                    # Fallback: flatten and reshape
                    trajectory_pred = pred_numpy.reshape(-1, 2)
                
                print(f"Extracted trajectory shape: {trajectory_pred.shape}")
                pred_list = trajectory_pred.tolist()
                print(f"Predictions list length: {len(pred_list)}")
                return pred_list
            else:
                print("ERROR: evaluate_real_time_data returned None")
                return []
            
        except Exception as e:
            print(f"ERROR in trajectory prediction: {e}")
            import traceback
            print(traceback.format_exc())
            return []
    
    def create_ego_frame(self):
        """Create ego frame from robot TF data"""
        if self.latest_robot_tf is None:
            return False
        
        ego_frame = {
            'timestamp': self.latest_robot_tf.header.stamp,
            'position': {
                'x': self.latest_robot_tf.transform.translation.x,
                'y': self.latest_robot_tf.transform.translation.y,
                'z': self.latest_robot_tf.transform.translation.z
            },
            'orientation': {
                'x': self.latest_robot_tf.transform.rotation.x,
                'y': self.latest_robot_tf.transform.rotation.y,
                'z': self.latest_robot_tf.transform.rotation.z,
                'w': self.latest_robot_tf.transform.rotation.w
            }
        }
        self.ego_frames.append(ego_frame)
        return True
    
    def create_camera_pose_frame(self):
        """Create camera pose frame from camera TF data"""
        if self.latest_camera_tf is None:
            return False
            
        camera_frame = {
            'timestamp': self.latest_camera_tf.header.stamp,
            'position': {
                'x': self.latest_camera_tf.transform.translation.x,
                'y': self.latest_camera_tf.transform.translation.y,
                'z': self.latest_camera_tf.transform.translation.z
            },
            'orientation': {
                'x': self.latest_camera_tf.transform.rotation.x,
                'y': self.latest_camera_tf.transform.rotation.y,
                'z': self.latest_camera_tf.transform.rotation.z,
                'w': self.latest_camera_tf.transform.rotation.w
            }
        }
        self.camera_frames.append(camera_frame)
        return True
    
    def create_local_frame(self, msg):
        """Create local frame from detection message"""
        local_frame = {
            'timestamp': msg.header.stamp,
            'persons': []
        }
        
        for person in msg.persons:
            person_data = {
                'id': getattr(person, 'id', ''),
                'body_parts': []
            }
            
            # Use body_pose.position as the primary position source
            if hasattr(person, 'body_pose') and hasattr(person.body_pose, 'position'):
                person_data['position'] = {
                    'x': person.body_pose.position.x,
                    'y': person.body_pose.position.y,
                    'z': person.body_pose.position.z
                }
            # Fallback to head_pose.position if body_pose is not available
            elif hasattr(person, 'head_pose') and hasattr(person.head_pose, 'position'):
                person_data['position'] = {
                    'x': person.head_pose.position.x,
                    'y': person.head_pose.position.y,
                    'z': person.head_pose.position.z
                }
            else:
                # Default position if no pose data available
                person_data['position'] = {
                    'x': 0.0,
                    'y': 0.0,
                    'z': 0.0
                }
            
            # Extract body parts
            if hasattr(person, 'body_parts'):
                for part in person.body_parts:
                    if hasattr(part, 'x') and hasattr(part, 'y'):
                        person_data['body_parts'].append({
                            'part_id': getattr(part, 'part_id', ''),
                            'x': part.x,
                            'y': part.y,
                            'confidence': getattr(part, 'confidence', 0.0)
                        })
            
            # Store additional pose information
            if hasattr(person, 'body_pose'):
                person_data['body_pose'] = {
                    'position': {
                        'x': person.body_pose.position.x,
                        'y': person.body_pose.position.y,
                        'z': person.body_pose.position.z
                    },
                    'orientation': {
                        'x': person.body_pose.orientation.x,
                        'y': person.body_pose.orientation.y,
                        'z': person.body_pose.orientation.z,
                        'w': person.body_pose.orientation.w
                    }
                }
            
            if hasattr(person, 'head_pose'):
                person_data['head_pose'] = {
                    'position': {
                        'x': person.head_pose.position.x,
                        'y': person.head_pose.position.y,
                        'z': person.head_pose.position.z
                    },
                    'orientation': {
                        'x': person.head_pose.orientation.x,
                        'y': person.head_pose.orientation.y,
                        'z': person.head_pose.orientation.z,
                        'w': person.head_pose.orientation.w
                    }
                }
            
            local_frame['persons'].append(person_data)
            
        self.local_frames.append(local_frame)
    
    def save_debug_data(self, X, predictions):
        """Save debug data to JSON file"""
        debug_data = {
            'timestamp': rospy.Time.now().to_sec(),
            'X': X.tolist() if hasattr(X, 'tolist') else X,
            'predictions': predictions,
            'num_local_frames': len(self.local_frames),
            'num_ego_frames': len(self.ego_frames),
            'num_camera_frames': len(self.camera_frames)
        }
        
        filename = f"debug_data_{rospy.Time.now().to_sec()}.json"
        with open(filename, 'w') as f:
            json.dump(debug_data, f, indent=2)

    def create_bbox(self, body_parts):
        min_x = min(part.x for part in body_parts)
        min_y = min(part.y for part in body_parts)
        max_x = max(part.x for part in body_parts)
        max_y = max(part.y for part in body_parts)
        return [min_x, min_y, max_x, max_y]

    def spin(self):
        rospy.loginfo('RealTimeDataCollector spinning...')
        rospy.spin()

if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=str, default="realeases/jta/checkpoint/checkpoint.pth.tar", 
                       help="Path to model checkpoint")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode")
    
    args = parser.parse_args()
    
    try:
        collector = RealTimeDataCollector(checkpoint_path=args.checkpoint)
        if args.debug:
            collector.debug = True
        collector.spin()
    except Exception as e:
        print(f"Error initializing collector: {e}")
        import traceback
        traceback.print_exc()
